version: '3.9'

services:
  db:
    image: postgres:15
    container_name: petclinic-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: petclinic
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/database.sql:/docker-entrypoint-initdb.d/database.sql  
    networks:
      - petnet

  pgadmin:
    image: dpage/pgadmin4
    container_name: petclinic-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin   
    networks:
      - petnet

  app:
    build: .
    container_name: petclinic-app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: petclinic
      JWT_SECRET: mySuperSecretKey
    volumes:
      - ./uploads:/app/uploads
    networks:
      - petnet

volumes:
  postgres_data:
  pgadmin_data:

networks:
  petnet:
